import {adminRequest} from './admin-worker.mjs';
import {videoRequest} from './video-worker.mjs';
// Public event-page metadata only. No credentials, scripts or cookies are forwarded.
const hosts=['partiful.com','goldendoko.com','eventbrite.com','eventbrite.ca','eventbrite.co.uk','ticketweb.com','ticketmaster.com','allevents.in','simpletix.com','ticketsource.us'];
function allowed(url){return url.protocol==='https:'&&!url.username&&!url.password&&(!url.port||url.port==='443')&&hosts.some(h=>url.hostname===h||url.hostname.endsWith('.'+h));}
function decode(s){return s.replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(Number(n)));}
export function imageFromHTML(html,base){for(const property of ['og:image:secure_url','og:image','twitter:image'])for(const tag of html.match(/<meta\b[^>]*>/gi)||[]){const attrs={};for(const m of tag.matchAll(/([\w:-]+)\s*=\s*(?:"([^"]*)"|'([^']*)')/g))attrs[m[1].toLowerCase()]=m[2]??m[3];if((attrs.property||attrs.name||'').toLowerCase()!==property||!attrs.content)continue;try{const u=new URL(decode(attrs.content),base);if(u.protocol==='https:'&&!u.username&&!u.password&&!/^\d+(?:\.\d+){3}$/.test(u.hostname)&&u.hostname.includes('.')&&!u.hostname.endsWith('.local'))return u.href}catch{}}return '';}
export default {async fetch(request,env,ctx){const requestURL=new URL(request.url);if(requestURL.pathname==='/admin'||requestURL.pathname==='/admin/'||requestURL.pathname.startsWith('/api/admin/'))return adminRequest(request,env);if(requestURL.pathname.startsWith('/api/videos/'))return videoRequest(request,env);if(requestURL.pathname!=='/api/event-preview')return env.ASSETS.fetch(request);if(request.method!=='GET')return new Response('Method not allowed',{status:405});let url;try{url=new URL(requestURL.searchParams.get('url'));if(!allowed(url))throw Error()}catch{return Response.json({ok:false,image:'',error:'Upload a flyer for this ticket provider.'},{status:400})}
 const key=new Request(requestURL.origin+'/api/event-preview?url='+encodeURIComponent(url.href));const cache=caches.default;const cached=await cache.match(key);if(cached)return cached;
 try{let response;for(let i=0;i<4;i++){response=await fetch(url.href,{redirect:'manual',headers:{Accept:'text/html','User-Agent':'DJ-Sarif-Event-Preview/1.0'},signal:AbortSignal.timeout(7000)});if(response.status>=300&&response.status<400){url=new URL(response.headers.get('location'),url);if(!allowed(url))throw Error();continue}break}if(!response.ok||!response.headers.get('content-type')?.includes('text/html'))throw Error();const reader=response.body.getReader(),chunks=[];let length=0;while(true){const part=await reader.read();if(part.done)break;length+=part.value.length;if(length>1000000){await reader.cancel();break}chunks.push(part.value)}const bytes=new Uint8Array(chunks.reduce((n,c)=>n+c.length,0));let offset=0;for(const c of chunks){bytes.set(c,offset);offset+=c.length}const image=imageFromHTML(new TextDecoder().decode(bytes),url.href);const result=Response.json({ok:true,image},{headers:{'Cache-Control':'public,max-age='+ (image?21600:300),'X-Content-Type-Options':'nosniff'}});ctx.waitUntil(cache.put(key,result.clone()));return result;
 }catch{return Response.json({ok:false,image:'',error:'No flyer available; upload one in the dashboard.'},{status:502})}}
};
