import {adminRequest} from './admin-worker.mjs';
import {videoRequest} from './video-worker.mjs';
// Public event-page metadata only. No credentials, scripts or cookies are forwarded.
// Accept public HTTPS event sites, while rejecting local/network targets and credentials.
export function allowed(url){const h=url.hostname.toLowerCase();return url.protocol==='https:'&&!url.username&&!url.password&&(!url.port||url.port==='443')&&h.length<254&&/^[a-z0-9-]+(?:\.[a-z0-9-]+)+$/.test(h)&&!/^\d+(?:\.\d+){3}$/.test(h)&&!/(?:^|\.)(localhost|local|internal|test|invalid|example|onion)$/.test(h);}
function publicIP(ip){if(ip.includes(':'))return /^(?:2|3)[0-9a-f]{0,3}:/i.test(ip)&&!/^2001:(?:0:|db8:)/i.test(ip);const n=ip.split('.').map(Number);return n.length===4&&n.every(v=>Number.isInteger(v)&&v>=0&&v<=255)&&![0,10,127].includes(n[0])&&n[0]<224&&!(n[0]===169&&n[1]===254)&&!(n[0]===172&&n[1]>=16&&n[1]<=31)&&!(n[0]===192&&(n[1]===168||n[1]===0))&&!(n[0]===100&&n[1]>=64&&n[1]<=127)&&!(n[0]===198&&(n[1]===18||n[1]===19));}
async function publicHost(url,signal){if(!allowed(url))throw Error('Invalid target');const answers=await Promise.all(['A','AAAA'].map(async type=>{const r=await fetch('https://cloudflare-dns.com/dns-query?name='+encodeURIComponent(url.hostname)+'&type='+type,{headers:{Accept:'application/dns-json'},signal});if(!r.ok)throw Error('DNS unavailable');return (await r.json()).Answer||[];}));const ips=answers.flat().filter(a=>a.type===1||a.type===28);if(!ips.length||ips.some(a=>!publicIP(a.data)))throw Error('Non-public target');}
function decode(s){return s.replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(Number(n)));}
export function imageFromHTML(html,base){for(const property of ['og:image:secure_url','og:image','twitter:image'])for(const tag of html.match(/<meta\b[^>]*>/gi)||[]){const attrs={};for(const m of tag.matchAll(/([\w:-]+)\s*=\s*(?:"([^"]*)"|'([^']*)')/g))attrs[m[1].toLowerCase()]=m[2]??m[3];if((attrs.property||attrs.name||'').toLowerCase()!==property||!attrs.content)continue;try{const u=new URL(decode(attrs.content),base);if(u.protocol==='https:'&&!u.username&&!u.password&&!/^\d+(?:\.\d+){3}$/.test(u.hostname)&&u.hostname.includes('.')&&!u.hostname.endsWith('.local'))return u.href}catch{}}return '';}
function plain(value,max=300){return typeof value==='string'?decode(value).replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim().slice(0,max):'';}
export function metadataFromHTML(html,base){
 const meta={};for(const tag of html.match(/<meta\b[^>]*>/gi)||[]){const attrs={};for(const m of tag.matchAll(/([\w:-]+)\s*=\s*(?:"([^"]*)"|'([^']*)')/g))attrs[m[1].toLowerCase()]=m[2]??m[3];const key=(attrs.property||attrs.name||'').toLowerCase();if(key&&!meta[key])meta[key]=attrs.content||'';}
 let event;function walk(v,depth=0){if(!v||depth>12||event)return;if(Array.isArray(v)){v.slice(0,100).forEach(x=>walk(x,depth+1));return;}if(typeof v!=='object')return;if([].concat(v['@type']||[]).some(t=>typeof t==='string'&&/(?:^|\/)\w*Event$/.test(t))){event=v;return;}for(const x of Object.values(v))walk(x,depth+1);}
 for(const m of html.matchAll(/<script\b[^>]*type\s*=\s*["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){try{walk(JSON.parse(m[1]));}catch{}}
 const loc=event?.location;const place=Array.isArray(loc)?loc[0]:loc;const addr=place?.address;const address=typeof addr==='string'?addr:addr?[addr.streetAddress,addr.addressLocality,addr.addressRegion,addr.postalCode].filter(Boolean).join(', '):'';
 const rawImage=Array.isArray(event?.image)?event.image[0]:event?.image;let image=imageFromHTML(html,base);if(!image&&rawImage){try{const u=new URL(typeof rawImage==='string'?rawImage:rawImage.url,base);if(allowed(u))image=u.href;}catch{}}
 return {image,title:plain(event?.name||meta['og:title']||meta['twitter:title']||html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1],180),description:plain(event?.description||meta['og:description']||meta.description,500),venue:plain(typeof place==='string'?place:place?.name,180),address:plain(address),startDate:plain(event?.startDate,80)};
}
export default {async fetch(request,env,ctx){const requestURL=new URL(request.url);if(requestURL.pathname==='/admin'||requestURL.pathname==='/admin/'||requestURL.pathname.startsWith('/api/admin/'))return adminRequest(request,env);if(requestURL.pathname.startsWith('/api/videos/'))return videoRequest(request,env);if(requestURL.pathname!=='/api/event-preview')return env.ASSETS.fetch(request);if(request.method!=='GET')return new Response('Method not allowed',{status:405});let url;try{url=new URL(requestURL.searchParams.get('url'));if(!allowed(url))throw Error()}catch{return Response.json({ok:false,image:'',error:'Use a public HTTPS event link, or upload a flyer.'},{status:400})}
 const key=new Request(requestURL.origin+'/api/event-preview?v=2&url='+encodeURIComponent(url.href));const cache=caches.default;const cached=await cache.match(key);if(cached)return cached;
 try{const signal=AbortSignal.timeout(9000);let response;for(let i=0;i<4;i++){await publicHost(url,signal);response=await fetch(url.href,{redirect:'manual',headers:{Accept:'text/html','User-Agent':'DJ-Sarif-Event-Preview/1.0'},signal});if(response.status>=300&&response.status<400){url=new URL(response.headers.get('location'),url);if(!allowed(url))throw Error();continue}break}if(!response.ok||!response.headers.get('content-type')?.includes('text/html'))throw Error();const reader=response.body.getReader(),chunks=[];let length=0;while(true){const part=await reader.read();if(part.done)break;length+=part.value.length;if(length>1000000){await reader.cancel();break}chunks.push(part.value)}const bytes=new Uint8Array(chunks.reduce((n,c)=>n+c.length,0));let offset=0;for(const c of chunks){bytes.set(c,offset);offset+=c.length}const metadata=metadataFromHTML(new TextDecoder().decode(bytes),url.href);const image=metadata.image;const result=Response.json({ok:true,...metadata},{headers:{'Cache-Control':'public,max-age='+ (image?21600:300),'X-Content-Type-Options':'nosniff'}});ctx.waitUntil(cache.put(key,result.clone()));return result;
 }catch{return Response.json({ok:false,image:'',error:'No flyer available; upload one in the dashboard.'},{status:502})}}
};
