name = "djsarif-site"
pages_build_output_dir = "."
compatibility_date = "2026-01-20"
[[r2_buckets]]
binding = "VIDEOS"
bucket_name = "djsarif-videos"
[[env.production.r2_buckets]]
binding = "VIDEOS"
bucket_name = "djsarif-videos"
[[env.preview.r2_buckets]]
binding = "VIDEOS"
bucket_name = "djsarif-videos"
